language: c

python:
  - "3.4"

sudo: required

compiler:
  - clang
  - gcc

before_install:
  - sudo -H pip install https://github.com/mesonbuild/meson/releases/download/0.44.1/meson-0.44.1.tar.gz
  - wget -P /tmp https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip /tmp/ninja-linux -d /tmp
  - sudo cp /tmp/ninja /usr/bin

install:
  - sudo apt-get install -q -y libsdl-image1.2 libsdl-image1.2-dev libsdl1.2-dev libsdl1.2debian libsdl2-2.0-0

script:
  - meson build
  - ninja -v -C build
