language: c

dist: trusty
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ninja python3 python3-pip build-essential
  - sudo -H pip3 install meson

install:
  - sudo apt-get install -q -y libsdl2-dev libsdl2-image-dev

script:
  - meson build
  - ninja -C build
