language: c

dist: trusty
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3 python3-pip build-essential
  - sudo -H pip3 install meson
  - wget -P /tmp https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip /tmp/ninja-linux -d /tmp
  - sudo cp /tmp/ninja /usr/bin

install:
  - sudo apt-get install -q -y libsdl-image1.2 libsdl-image1.2-dev libsdl1.2-dev libsdl1.2debian libsdl2-2.0-0

script:
  - meson build
  - ninja -C build
